// Code generated by MockGen. DO NOT EDIT.
// Source: currency_service.go
//
// Generated by this command:
//
//	mockgen -source=currency_service.go -destination=mocks/mock_currency_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICurrencyRepository is a mock of ICurrencyRepository interface.
type MockICurrencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICurrencyRepositoryMockRecorder
	isgomock struct{}
}

// MockICurrencyRepositoryMockRecorder is the mock recorder for MockICurrencyRepository.
type MockICurrencyRepositoryMockRecorder struct {
	mock *MockICurrencyRepository
}

// NewMockICurrencyRepository creates a new mock instance.
func NewMockICurrencyRepository(ctrl *gomock.Controller) *MockICurrencyRepository {
	mock := &MockICurrencyRepository{ctrl: ctrl}
	mock.recorder = &MockICurrencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICurrencyRepository) EXPECT() *MockICurrencyRepositoryMockRecorder {
	return m.recorder
}

// GetEnabledCurrencies mocks base method.
func (m *MockICurrencyRepository) GetEnabledCurrencies(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledCurrencies", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledCurrencies indicates an expected call of GetEnabledCurrencies.
func (mr *MockICurrencyRepositoryMockRecorder) GetEnabledCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledCurrencies", reflect.TypeOf((*MockICurrencyRepository)(nil).GetEnabledCurrencies), ctx)
}
