// Code generated by MockGen. DO NOT EDIT.
// Source: quote_service.go
//
// Generated by this command:
//
//	mockgen -source=quote_service.go -destination=mocks/mock_quote_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
	domain "github.com/spenderella/currency-quotes-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIQuoteRepository is a mock of IQuoteRepository interface.
type MockIQuoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIQuoteRepositoryMockRecorder
	isgomock struct{}
}

// MockIQuoteRepositoryMockRecorder is the mock recorder for MockIQuoteRepository.
type MockIQuoteRepositoryMockRecorder struct {
	mock *MockIQuoteRepository
}

// NewMockIQuoteRepository creates a new mock instance.
func NewMockIQuoteRepository(ctrl *gomock.Controller) *MockIQuoteRepository {
	mock := &MockIQuoteRepository{ctrl: ctrl}
	mock.recorder = &MockIQuoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuoteRepository) EXPECT() *MockIQuoteRepositoryMockRecorder {
	return m.recorder
}

// ClaimPendingQuoteUpdates mocks base method.
func (m *MockIQuoteRepository) ClaimPendingQuoteUpdates(ctx context.Context, limit int) ([]domain.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimPendingQuoteUpdates", ctx, limit)
	ret0, _ := ret[0].([]domain.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimPendingQuoteUpdates indicates an expected call of ClaimPendingQuoteUpdates.
func (mr *MockIQuoteRepositoryMockRecorder) ClaimPendingQuoteUpdates(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimPendingQuoteUpdates", reflect.TypeOf((*MockIQuoteRepository)(nil).ClaimPendingQuoteUpdates), ctx, limit)
}

// CreateQuoteUpdate mocks base method.
func (m *MockIQuoteRepository) CreateQuoteUpdate(ctx context.Context, baseCurrency, quoteCurrency, idempotencyKey string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateQuoteUpdate", ctx, baseCurrency, quoteCurrency, idempotencyKey)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateQuoteUpdate indicates an expected call of CreateQuoteUpdate.
func (mr *MockIQuoteRepositoryMockRecorder) CreateQuoteUpdate(ctx, baseCurrency, quoteCurrency, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateQuoteUpdate", reflect.TypeOf((*MockIQuoteRepository)(nil).CreateQuoteUpdate), ctx, baseCurrency, quoteCurrency, idempotencyKey)
}

// GetQuoteUpdateByID mocks base method.
func (m *MockIQuoteRepository) GetQuoteUpdateByID(ctx context.Context, id uuid.UUID) (domain.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuoteUpdateByID", ctx, id)
	ret0, _ := ret[0].(domain.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuoteUpdateByID indicates an expected call of GetQuoteUpdateByID.
func (mr *MockIQuoteRepositoryMockRecorder) GetQuoteUpdateByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuoteUpdateByID", reflect.TypeOf((*MockIQuoteRepository)(nil).GetQuoteUpdateByID), ctx, id)
}

// GetQuoteUpdateLatest mocks base method.
func (m *MockIQuoteRepository) GetQuoteUpdateLatest(ctx context.Context, baseCurrency, quoteCurrency string) (domain.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuoteUpdateLatest", ctx, baseCurrency, quoteCurrency)
	ret0, _ := ret[0].(domain.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuoteUpdateLatest indicates an expected call of GetQuoteUpdateLatest.
func (mr *MockIQuoteRepositoryMockRecorder) GetQuoteUpdateLatest(ctx, baseCurrency, quoteCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuoteUpdateLatest", reflect.TypeOf((*MockIQuoteRepository)(nil).GetQuoteUpdateLatest), ctx, baseCurrency, quoteCurrency)
}

// GetUndoneQuoteUpdates mocks base method.
func (m *MockIQuoteRepository) GetUndoneQuoteUpdates(ctx context.Context) ([]domain.Quote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUndoneQuoteUpdates", ctx)
	ret0, _ := ret[0].([]domain.Quote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUndoneQuoteUpdates indicates an expected call of GetUndoneQuoteUpdates.
func (mr *MockIQuoteRepositoryMockRecorder) GetUndoneQuoteUpdates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUndoneQuoteUpdates", reflect.TypeOf((*MockIQuoteRepository)(nil).GetUndoneQuoteUpdates), ctx)
}

// MarkDone mocks base method.
func (m *MockIQuoteRepository) MarkDone(ctx context.Context, id uuid.UUID, rate decimal.Decimal, providerTime, fetchedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDone", ctx, id, rate, providerTime, fetchedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDone indicates an expected call of MarkDone.
func (mr *MockIQuoteRepositoryMockRecorder) MarkDone(ctx, id, rate, providerTime, fetchedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDone", reflect.TypeOf((*MockIQuoteRepository)(nil).MarkDone), ctx, id, rate, providerTime, fetchedAt)
}

// MarkFailed mocks base method.
func (m *MockIQuoteRepository) MarkFailed(ctx context.Context, id uuid.UUID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockIQuoteRepositoryMockRecorder) MarkFailed(ctx, id, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockIQuoteRepository)(nil).MarkFailed), ctx, id, reason)
}

// MockICurrencyService is a mock of ICurrencyService interface.
type MockICurrencyService struct {
	ctrl     *gomock.Controller
	recorder *MockICurrencyServiceMockRecorder
	isgomock struct{}
}

// MockICurrencyServiceMockRecorder is the mock recorder for MockICurrencyService.
type MockICurrencyServiceMockRecorder struct {
	mock *MockICurrencyService
}

// NewMockICurrencyService creates a new mock instance.
func NewMockICurrencyService(ctrl *gomock.Controller) *MockICurrencyService {
	mock := &MockICurrencyService{ctrl: ctrl}
	mock.recorder = &MockICurrencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICurrencyService) EXPECT() *MockICurrencyServiceMockRecorder {
	return m.recorder
}

// IsSupported mocks base method.
func (m *MockICurrencyService) IsSupported(code string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSupported", code)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSupported indicates an expected call of IsSupported.
func (mr *MockICurrencyServiceMockRecorder) IsSupported(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSupported", reflect.TypeOf((*MockICurrencyService)(nil).IsSupported), code)
}

// MockIRatesProvider is a mock of IRatesProvider interface.
type MockIRatesProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIRatesProviderMockRecorder
	isgomock struct{}
}

// MockIRatesProviderMockRecorder is the mock recorder for MockIRatesProvider.
type MockIRatesProviderMockRecorder struct {
	mock *MockIRatesProvider
}

// NewMockIRatesProvider creates a new mock instance.
func NewMockIRatesProvider(ctrl *gomock.Controller) *MockIRatesProvider {
	mock := &MockIRatesProvider{ctrl: ctrl}
	mock.recorder = &MockIRatesProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRatesProvider) EXPECT() *MockIRatesProviderMockRecorder {
	return m.recorder
}

// GetRate mocks base method.
func (m *MockIRatesProvider) GetRate(ctx context.Context, baseCurrency, quoteCurrency string) (decimal.Decimal, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", ctx, baseCurrency, quoteCurrency)
	ret0, _ := ret[0].(decimal.Decimal)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRate indicates an expected call of GetRate.
func (mr *MockIRatesProviderMockRecorder) GetRate(ctx, baseCurrency, quoteCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockIRatesProvider)(nil).GetRate), ctx, baseCurrency, quoteCurrency)
}
